/**
 * Created by hien.phanthe on 2/24/17.
 */
export const GO_SIGNUP = "GO_SIGNUP";
export const GO_LOGOUT = "GO_LOGOUT";
export const STORE_USER = "STORE_USER";
export const GET_ALL_CANDIDATES = "GET_ALL_CANDIDATES";
export const GET_ALL_CANDIDATES_SUCCESS = "GET_ALL_CANDIDATES_SUCCESS";
export const GET_ALL_CANDIDATES_ERROR = "GET_ALL_CANDIDATES_ERROR";
export const GET_CANDIDATE_DETAIL = "GET_CANDIDATE_DETAIL";

export const Update_CANDIDATE_SUCCESS = "Update_CANDIDATE_SUCCESS";
export const Update_CANDIDATE_ERROR = "Update_CANDIDATE_ERROR";

export const CREATE_CANDIDATE_SUCCESS = "CREATE_CANDIDATE_SUCCESS";
export const CREATE_CANDIDATE_ERROR = "CREATE_CANDIDATE_ERROR";


export const ARCHIVE_CANDIDATE_SUCCESS = "ARCHIVE_CANDIDATE_SUCCESS";
export const ARCHIVE_CANDIDATE_ERROR = "ARCHIVE_CANDIDATE_ERROR";

